source "http://rubygems.org"

gem 'sinatra'
gem 'embedify', path: '../../'
gem 'shotgun'
gem 'thin'
gem 'sinatra-jsonp', :require => 'sinatra/jsonp'
gem 'em-synchrony'
gem 'em-http-request'
gem 'sinatra-synchrony'
